spring:
  datasource:
    url: jdbc:mysql://47.113.188.108:3306/match_trading?serverTimezone=Asia/Shanghai
    username: root
    password: Zym.141592
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/star/counter/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null